# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta', models.CharField(max_length=16)),
                ('tarjeta_debito', models.BooleanField(default=False)),
                ('vencimiento', models.DateField(null=True)),
                ('cvv', models.CharField(max_length=3)),
                ('monto', models.IntegerField()),
                ('entidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('titular', models.CharField(max_length=30)),
                ('monto', models.IntegerField(default=0)),
                ('returnMonto', models.CharField(blank=True, max_length=30, null=True)),
                ('returnDescription', models.CharField(blank=True, max_length=30, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pago.Suministro'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago.Tarjeta'),
        ),
    ]
