# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-19 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnSuministro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('titular', models.CharField(max_length=30)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pago',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='returnDescription',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='returnMonto',
        ),
    ]
