# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-19 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_auto_20190719_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='operacion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tarjeta',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tarjeta_debito',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tipo_tarjeta',
        ),
    ]
