# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-19 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0005_pago2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago2',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
